spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql:testaxis

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: d3e47fc2ddd966fa4352
            clientSecret: 3bc0f6b8332f93076354c2a5bada2f5a05aea60d
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB

app:
  auth:
    tokenSecret: u0fNVcI5VfhURTascNxULCBBcw4ac8+8pdKQPEvkkmOqbyKj05PRy+cqMnqGDdHwanBd1/+jk4qBBuZ3F+cGUQ== # For development, production should override
    tokenExpirationMsec: 8640000000
  oauth2:
    authorizedRedirectUris:
      - http://localhost:4000/auth/token
      - https://testaxis.io/auth/token
