name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: textaxis-ci
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Cache Gradle packages
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: ./gradlew build -x check --info
    - name: Run tests with Gradle
      run: ./gradlew test --info
      env:
        PG_HOST: localhost
        PG_USER: postgres
        PG_DATABASE: textaxis-ci
        PG_PASSWORD: postgres
        PG_PORT: ${{ job.services.postgres.ports['5432'] }}
    - name: Run detekt with Gradle
      run: ./gradlew detekt
    - name: Run ktlint with Gradle
      run: ./gradlew ktlintCheck
    - name: Upload test results to TestAxis
      run: ./src/main/resources/static/testaxis-upload.bash -s build/test-results/test/
      # Use `bash <(curl -s http://localhost:8080/testaxis-upload.bash)` to retrieve the upload script for other projects
